name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version for the release"
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'

    - name: Install .NET Runtime Pack
      run: |
        dotnet workload install

    - name: Restore NuGet Dependencies
      run: nuget restore SpotControl.sln

    - name: Build SpotControl (Release)
      run: dotnet build SpotControl.sln --configuration Release

    - name: Publish normal expanded version
      run: dotnet publish SpotControl.csproj -c Release -o SpotControl-publish-expanded --no-restore

    - name: Publish (single file)
      run: |
        dotnet publish SpotControl.csproj -c Release -o ./SpotControl-publish-single -p:PublishSingleFile=true -p:RuntimeIdentifier=win-x64 -p:SelfContained=true -p:IncludeNativeLibrariesForSelfExtract=true --no-restore

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ inputs.version }}
        name: SpotControl Release ${{ inputs.version }}
        files: |
          SpotControl-publish-expanded/**
          SpotControl-publish-single/**
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
